---
# tasks file for roles/prometheus
- name: update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus
- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus
- name: check prometheus alerts configuration dir exists
  file: 
    path: "{{ prometheus_dir_configuration }}/alerts"
    state: directory
- name: copy prometheus alerts configuration file
  copy:
    src: alerts.yml
    dest: "{{ prometheus_dir_configuration }}/alerts/alerts.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus
- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
