namespace: sre-cource-student-81

srecourseapi:
  name: srecourseapi
  image:
    repository: ghcr.io/ldest/sre-course/api
    pullPolicy: IfNotPresent
    tag: f0135e1
  labels:
    app: srecourseapi
  env:
    ASPNETCORE_URLS: "http://*:8080"
    DOTNET_ENVIRONMENT: Development # Development|Production
    CONNECTIONSTRINGS__PGCONNECTION: "Server=91.185.85.11;Port=5000;Userid=weather-user;Password=weather-user-pass;Timeout=15;SslMode=Prefer;Database=weather"
  replicas: 3
  ports:
    internal: 8080
    external: 80
  ingress:
    host: "app.pub.sre.lab"
    prefix: ""
  resources:
    requests:
      cpu: 33m
      memory: 128M
    limits:
      cpu: 33m
      memory: 256M


