---
- name: remove_cluster.yml | PostgreSQL Cluster Play
  hosts: postgres_cluster
  become: true
  vars_files:
    - vars/main.yml
    - vars/{{ ansible_os_family }}.yml
  tasks:
    - block:
        - name: Stop Patroni service
          ansible.builtin.service:
            name: patroni
            state: stopped
            enabled: false
        - name: Delete PostgreSQL database content
          ansible.builtin.file:
            path: "{{ postgresql_data_dir }}"
            state: absent
      when: remove_postgres | default(true) | bool
      ignore_errors: true

- name: remove_cluster.yml | Etcd Cluster Play
  hosts: etcd_cluster
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - block:
        - name: Stop Etcd service
          ansible.builtin.service:
            name: etcd
            state: stopped
            enabled: false
        - name: Delete Etcd content
          ansible.builtin.file:
            path: "{{ etcd_data_dir }}/member"
            state: absent
      when: remove_etcd | default(true) | bool
      ignore_errors: true
